# Generated by Django 2.2.5 on 2024-07-03 00:40

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cargo', models.CharField(max_length=40, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(choices=[('1', 'Uma aula semanal'), ('2', 'Duas aulas semanais'), ('3', 'Três aulas semanais')], max_length=20, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('servico', models.CharField(max_length=30, verbose_name='Serviço')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plano', verbose_name='Plano')),
                ('servico', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Servico', verbose_name='Serviço')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('hora_trabalhadas', models.IntegerField(verbose_name='Horas/Semana')),
                ('bio', models.TextField(max_length=100, verbose_name='Bio')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem')),
                ('face', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('insta', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('exercicio', models.CharField(max_length=100, verbose_name='Exercício')),
                ('series', models.IntegerField(verbose_name='Séries')),
                ('repeticoes', models.IntegerField(verbose_name='Repetições')),
                ('carga', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carga')),
                ('observacoes', models.TextField(max_length=100, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha de Treino',
                'verbose_name_plural': 'Fichas de Treino',
            },
        ),
        migrations.CreateModel(
            name='FichaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IMC')),
                ('gordura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gordura')),
                ('observacoes', models.TextField(max_length=100, verbose_name='Observações')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha de Avaliação',
                'verbose_name_plural': 'Fichas de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualiação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.CharField(choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00')], max_length=5, verbose_name='Hora')),
                ('status', models.CharField(default='Agendado', max_length=20, verbose_name='Status')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('data', 'hora', 'paciente')},
            },
        ),
    ]
