# Generated by Django 2.2.5 on 2024-07-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaavaliacao',
            name='altura',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='fichaavaliacao',
            name='gordura',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Gordura'),
        ),
        migrations.AlterField(
            model_name='fichaavaliacao',
            name='imc',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='fichaavaliacao',
            name='peso',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='fichatreino',
            name='carga',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Carga'),
        ),
    ]
